# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5bae0b6332ee11b5576f6566e10df37a077c87678fcaa8c5acea81d00d8069ddce6293ba605cc6770d6506c6e6b26f715bdcb0cab3320e041b115fe84bbfb3c

test:
  secret_key_base: bc1a29c70c1f885df62dda35aa27bd6a850b3baff0592e9800a34eef3a9d6d44d52d5def2617f5f9751845ddcbf15093d8fb05745a20d862e88405787e1944b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
